//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absent
    {
        public int id { get; set; }
        public string Member_id { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public string Pewsent_Absent { get; set; }
        public string with_letter { get; set; }
        public string Date { get; set; }
    }
}
