//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAttendance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database_studentContainer : DbContext
    {
        public database_studentContainer()
            : base("name=database_studentContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student_Details> Student_Details { get; set; }
        public DbSet<Absent> Absents { get; set; }
        public DbSet<Absent_swami> Absent_swami { get; set; }
        public DbSet<login> logins { get; set; }
    }
}
