//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAttendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        public int id { get; set; }
        public string Member_id { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public string House { get; set; }
    }
}
